version: '3.1'

services: 
  db: 
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment: 
      SA_PASSWORD: "123"
      ACCEPT_EULA: "Y"
    ports: 
      - "1433:1433"
  redis: 
    image: redis
    ports: 
      - "6379:6379"
  node: 
    image: node:18-alpine
    volumes: 
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports: 
      - "3000:3000"
    depends_on: 
      - db
      - redis
